ALTER TYPE "JobCategory" ADD VALUE IF NOT EXISTS 'INTERNSHIP';
ALTER TYPE "JobCategory" ADD VALUE IF NOT EXISTS 'PROJECT_ASSISTANT';
ALTER TYPE "JobCategory" ADD VALUE IF NOT EXISTS 'LAB_ASSISTANT';
ALTER TYPE "JobCategory" ADD VALUE IF NOT EXISTS 'PEER_TUTOR';
